### ISSUE TITLE
[BUG] MetaMask is not shown on Chrome

### ISSUE THREAD

**Issue by oceanByte** [deltaDAO/portal-euprogigant#11]
## Summary
MetaMask is not shown as a select option when you have not installed it yet. You need to install it, refresh the page and then it is shown as a select option.

## Current Behavior
If you visit the portal first, install MetaMask then as described (without closing the portal) and go back to proceed, the portal does not know that MetaMask is available now.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/75223088/169642802-227f28d6-8d7d-47f1-a185-a4056496815d.png">

## Expected Behavior
The page should either auto-refresh or ask the user to refresh the page to enable MetaMask for the portal.

## Steps to Reproduce
Requirements: Chrome without MetaMask installed (might also be true for other browsers)
1. Visit https://euprogigant.portal.minimal-gaia-x.eu/
2. Install MetaMask
3. Click on "Connect Wallet"
4. There is no MetaMask connect available
  
## Anything else
- Our web app does not recognize the new plugin until the page is refreshed
- Maybe an easy solution: Always show MetaMask as an option. If it is not installed, throw an error.

**Comment by LucaMilanese90** [comment]
I opened this issue yesterday, this should solve the problem when you download MetaMask during the onboarding process: https://github.com/deltaDAO/mvg-portal/issues/129
For the generic case where you just install it on your own, I have to check how the library works, not sure you can always display an option, but we could add a message on top of the login window saying you need to refresh the page if you just installed MM, maybe that would be enough.

**Comment by oceanByte** [comment]
Yes, I saw your post there already. I should have referred to it, but I wanted to make sure to raise it in this specific portal as well as it was mentioned after my presentation that they had this issue with the onboarding. 

A refresh option was also discussed if there is no easier solution to it. At least we should let the user know that they need to do something after they installed MetaMask. A simple text helps!
